name: Build, Push and Deploy

on:
  push:
    paths-ignore:
      - 'devops/**'
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: true

env:
  extensions: gd, pcntl, iconv, curl, intl, xml, mbstring, bcmath, sodium, opcache, zip, redis, ast, apcu

jobs:
  rector:
    name: Rector
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          tools: rector/rector
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: Execute
        shell: bash
        run: |
          rector process .
  phpinsights:
    name: PHP Insights
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          tools: nunomaduro/phpinsights
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: Execute
        shell: bash
        run: |
          phpinsights analyse -n --ansi --format=github-action .
  #  phpstan:
  #    name: PHP Stan
  #    runs-on: ubuntu-latest
  #    strategy:
  #      matrix:
  #        version: [ 8.0, 8.1 ]
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3
  #        with:
  #          token: ${{ secrets.GH_TOKEN }}
  #          submodules: recursive
  #      - name: Setup cache environment
  #        id: extcache
  #        uses: shivammathur/cache-extensions@v1
  #        with:
  #          php-version: ${{ matrix.version }}
  #          extensions: ${{ env.extensions }}
  #          key: 1
  #      - name: Cache extensions
  #        uses: actions/cache@v3
  #        with:
  #          path: ${{ steps.extcache.outputs.dir }}
  #          key: ${{ steps.extcache.outputs.key }}
  #          restore-keys: ${{ steps.extcache.outputs.key }}
  #      - name: Setup PHP with PECL extension
  #        uses: shivammathur/setup-php@v2
  #        with:
  #          php-version: ${{ matrix.version }}
  #          extensions: ${{ env.extensions }}
  #          tools: phpstan
  #        env:
  #          update: true
  #      - name: Get composer cache directory
  #        id: composer-cache
  #        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
  #      - name: Cache dependencies
  #        uses: actions/cache@v3
  #        with:
  #          path: ${{ steps.composer-cache.outputs.dir }}
  #          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
  #          restore-keys: ${{ runner.os }}-composer-
  #      - name: Composer Install
  #        shell: bash
  #        run: |
  #          composer install
  #      - name: Execute
  #        shell: bash
  #        run: |
  #          phpstan analyse --memory-limit=1024M -c phpstan.neon .
  phan:
    name: Phan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          tools: phan
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: Execute
        shell: bash
        run: |
          phan
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          tools: vimeo/psalm
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: Execute
        shell: bash
        run: |
          psalm
  php-cs-fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          tools: php-cs-fixer
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: Execute
        shell: bash
        run: |
          PHP_CS_FIXER_IGNORE_ENV=1 php-cs-fixer fix
  unused:
    name: PHP Unused Scanner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          tools: insolita/unused-scanner
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: Execute
        shell: bash
        run: |
          unused_scanner
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: PHP Security Checker
        uses: symfonycorp/security-checker-action@v2
        with:
          lock: composer.lock
      - name: Antimalware Scanner
        shell: bash
        run: |
          wget https://raw.githubusercontent.com/marcocesarato/PHP-Antimalware-Scanner/master/dist/scanner --no-check-certificate -O /usr/local/bin/amscanner.phar
          printf "#!/bin/bash\nphp /usr/local/bin/amscanner.phar \$@" > /usr/local/bin/amscanner
          chmod u+x,g+x /usr/local/bin/amscanner.phar /usr/local/bin/amscanner
          amscanner --no-report --path-whitelist="/var/www/scanner-whitelist.json"
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8.0, 8.1 ]
    needs: [ rector, phpinsights, phan, psalm, php-cs-fixer, unused, security-check ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
      - name: Setup cache environment
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          key: 1
      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          extensions: ${{ env.extensions }}
          tools: phpunit
        env:
          update: true
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Composer Install
        shell: bash
        run: |
          composer install
      - name: Test
        shell: bash
        run: |
          phpunit
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          submodules: recursive
